version: '3'

services:
###> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-14}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
  database:
    image: convisdock/docker-mysql:1.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DB:-symfony}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - symfony
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  symfony:
    driver: bridge # default but good practice to inlcude for clarity
